[package]
name = "rust_nazopuyo_solver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_nazopuyo_solver"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# fxhash = "0.2.1"
colored = "2"